[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name = "klondike-ai"
version = "0.1.0"
authors = [{name = "Klondike AI Team"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"

[tool.maturin]
bindings = "pyo3"
module-name = "klondike_core"

