[package]
name = "klondike-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
klondike-core = { path = "../core" }
klondike-ai = { path = "../ai" }
colored.workspace = true
signal-hook.workspace = true